In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=['The glass of juice',
'The glass of milk',
    'I am a good boy',
    'I am a good developer',
    'your videos are good',
    'understand the meaning of words',
    'the cup of tea'
]

In [3]:
# define the vocabulary size

voc_size=10000

In [5]:
#one hot representation

one_hot_repr= [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[5555, 9682, 5046, 4359, 5248],
 [5555, 9682, 5046, 4359, 6375],
 [4643, 136, 7655, 4359]]

In [11]:
## word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequence
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [9]:
import numpy as np


In [13]:
sent_length=8
embedded_docs= pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

print(embedded_docs)

[[   0    0    0 5555 9682 5046 4359 5248]
 [   0    0    0 5555 9682 5046 4359 6375]
 [   0    0    0    0 4643  136 7655 4359]]


In [14]:
# feature representation

dim=10


In [15]:
model= Sequential()
model.add(Embedding(voc_size, dim, input_length= sent_length))

model.compile('adam', 'mse')

C:\Users\aksha\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 521ms/step


array([[[-0.00812732,  0.04676015,  0.01140617,  0.01562519,
          0.02420009,  0.03163764, -0.03231229, -0.0459967 ,
         -0.0344682 , -0.03241243],
        [-0.00812732,  0.04676015,  0.01140617,  0.01562519,
          0.02420009,  0.03163764, -0.03231229, -0.0459967 ,
         -0.0344682 , -0.03241243],
        [-0.00812732,  0.04676015,  0.01140617,  0.01562519,
          0.02420009,  0.03163764, -0.03231229, -0.0459967 ,
         -0.0344682 , -0.03241243],
        [ 0.0416204 ,  0.03269492,  0.04142377, -0.04978353,
         -0.00360746, -0.04158509,  0.0223867 , -0.02613629,
         -0.03511479, -0.04783958],
        [ 0.03960797, -0.03517755,  0.04475013,  0.02115825,
         -0.031502  , -0.0186224 ,  0.03544584,  0.00960244,
          0.01127847,  0.01447764],
        [ 0.00434988, -0.01509998,  0.03210697, -0.04519321,
         -0.00681804, -0.00914443, -0.02585676,  0.00773082,
         -0.00588369, -0.02254607],
        [-0.02350969, -0.04591606, -0.03238674, -0.0